#!/usr/bin/env bash
#Install NGINX on a server

sudo apt update
sudo apt -y install nginx
sudo chmod 666 /var/www/html/index.nginx-debian.html
echo "Holberton School" > /var/www/html/index.nginx-debian.html
sudo touch /var/www/html/my404.html
sudo chmod 666 /var/www/html/my404.html
echo "Ceci n'est pas une page" > /var/www/html/my404.html
sudo sed -i 's/listen 80 default_server;/listen 80 default_server;\n  error_page 404 \/my404.html;\n  rewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;/' /etc/nginx/sites-available/default
sudo service nginx restart
