#!/usr/bin/env bash
#Install NGINX on a server

sudo apt -y update
sudo apt install -y haproxy
sudo chmod 666 /etc/default/haproxy
sudo echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo chmod 666 /etc/haproxy/haproxy.cfg
sudo echo "listen test
    bind 0.0.0.0:80
    balance roundrobin
    server 2531-web-01 34.75.232.143:80 check
    server 2531-web-02 34.75.165.238:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
