#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times
# but replaces line 9 with "Hi"
x=1
while [ $x -le 10 ]
do
    echo "Holberton School"
    if [ $x -eq 9 ]
    then
	echo "Hi"
    fi
    let "x++"
done
