#!/usr/bin/env bash
# This script is displaying numbers from 1 to 20
# except for the "unlucky" ones
x=1
while [ $x -le 20 ]
do
    case "$x" in
	4) echo "bad luck from China";;

	9) echo "bad luck from Japan";;

	17) echo "bad luck from Italy";;

	*) echo "$x";;
    esac

    let "x++"
done
